//! End-to-end smoke tests.
//!
//! These run the `fermut` binary against `examples/sample` (flat layout) and
//! `examples/monorepo_sample` (uv workspace with multiple member packages) to
//! confirm fermut walks both shapes. The flat-layout `run` test asserts that
//! the weak boundary test (`in_range`) leaves at least one survivor.

use std::path::PathBuf;

use assert_cmd::Command;
use predicates::str::contains;

fn sample_path() -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("examples/sample");
    p
}

fn monorepo_path() -> PathBuf {
    let mut p = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    p.push("examples/monorepo_sample");
    p
}

/// Recursively copy `src` into `dst` (both dirs). Used to run write-heavy tests
/// against a throwaway copy of a shared example tree, so learned artifacts
/// (`.coverage`, `.fermut/`) never land in the checked-in sample or race a
/// sibling test that reads the same tree.
///
/// Skips generated/ignored artifacts so the copy is a *pristine source tree*,
/// never a snapshot of another test's run. This matters because a stray
/// `.coverage` + `.coverage.fermut-fingerprints.json` in the copy makes the
/// copy's own `fermut coverage` treat the DB as up-to-date (the fingerprint is
/// content-based, so it can't tell the tree moved to a new absolute path) and
/// skip the rebuild — leaving `.coverage` file keys pointing at the *original*
/// tree. Every mutant then looks uncovered, the run is a vacuous 100%, and the
/// test that expected survivors fails. That state leaks in two ways this skip
/// list defends against: a dirty local working tree, and a parallel sibling
/// test writing into the shared checked-in sample (`cargo test` runs e2e tests
/// concurrently).
fn copy_dir(src: &std::path::Path, dst: &std::path::Path) {
    // Generated by fermut/pytest/coverage runs; never part of the source tree.
    const SKIP: &[&str] = &[
        ".coverage",
        ".coverage.fermut-fingerprints.json",
        "coverage.json",
        ".fermut",
        ".venv",
        "__pycache__",
        ".pytest_cache",
    ];
    std::fs::create_dir_all(dst).unwrap();
    for entry in std::fs::read_dir(src).unwrap() {
        let entry = entry.unwrap();
        let name = entry.file_name();
        // `.coverage.<pid>.<random>` parallel-write shards start with `.coverage`.
        let skip =
            SKIP.iter().any(|s| name == *s) || name.to_string_lossy().starts_with(".coverage");
        if skip {
            continue;
        }
        let from = entry.path();
        let to = dst.join(name);
        if entry.file_type().unwrap().is_dir() {
            copy_dir(&from, &to);
        } else {
            std::fs::copy(&from, &to).unwrap();
        }
    }
}

#[test]
fn list_emits_mutations() {
    Command::cargo_bin("fermut")
        .unwrap()
        .arg("list")
        .arg(sample_path().join("src"))
        .assert()
        .success()
        .stdout(contains("arith-op-swap"))
        .stdout(contains("boundary-shift"));
}

#[test]
fn list_emits_mutations_monorepo() {
    Command::cargo_bin("fermut")
        .unwrap()
        .arg("list")
        .arg(monorepo_path().join("packages"))
        .assert()
        .success()
        .stdout(contains("arith-op-swap"))
        .stdout(contains("boundary-shift"))
        .stdout(contains("pkg_a"))
        .stdout(contains("pkg_b"));
}

#[test]
#[ignore = "requires pytest + ty on PATH; enable once env is set up"]
fn run_finds_known_survivor() {
    // `run` writes `.fermut/` (cache, history) into the project; use a throwaway
    // copy so nothing lands in the checked-in sample or races a sibling test.
    let tmp = tempfile::tempdir().unwrap();
    let sample = tmp.path().join("sample");
    copy_dir(&sample_path(), &sample);
    Command::cargo_bin("fermut")
        .unwrap()
        .arg("run")
        .arg(sample.join("src"))
        .arg("--tests")
        .arg(sample.join("tests"))
        .arg("--no-ty-filter")
        .assert()
        .failure() // survivors → exit 1
        .stdout(contains("SURVIVED"));
}

#[test]
#[ignore = "requires pytest + pytest-cov + coverage on PATH; enable once env is set up"]
fn smart_order_builds_sidecar_and_keeps_verdict() {
    // Two runs: the first learns which tests kill mutants and writes
    // `.fermut/kill-order.json`; the second reads it to order tests. The
    // mutation result must be identical across both — ordering only changes
    // *which test runs first*, never the kill/survive verdict.
    //
    // Smart ordering only ever reorders *coverage-selected* tests, so the
    // feature is a no-op without per-test coverage: with the whole-tests-dir
    // sweep there is nothing to reorder and the sidecar is never written.
    // So we generate a per-test `.coverage` first and feed it to `run`. The
    // sample's `test_add`/`test_add_commutes` pair covers `add`'s mutated line
    // twice — the >1-test case the capture path needs.
    //
    // This test WRITES learned artifacts (`.coverage`, `.fermut/kill-order.json`)
    // beside the project, so run it against a throwaway copy of the sample rather
    // than the checked-in tree — otherwise those files linger as untracked and
    // could race a sibling e2e reading the same sample under `cargo test`'s
    // parallelism. The tempdir (and everything under it) is removed on drop, on
    // the happy path and on any panic below.
    let tmp = tempfile::tempdir().unwrap();
    let sample = tmp.path().join("sample");
    copy_dir(&sample_path(), &sample);

    let src = sample.join("src");
    let tests = sample.join("tests");
    // Kill-order sidecar lands at the project root's `.fermut/`.
    let sidecar = sample.join(".fermut").join("kill-order.json");
    let coverage = sample.join(".coverage");

    // Build the per-test coverage database (pytest-cov contexts).
    Command::cargo_bin("fermut")
        .unwrap()
        .arg("coverage")
        .arg(&sample)
        .assert()
        .success();
    assert!(
        coverage.exists(),
        "coverage step must write the .coverage database at {}",
        coverage.display()
    );

    let run = || {
        Command::cargo_bin("fermut")
            .unwrap()
            .arg("run")
            .arg(&src)
            .arg("--tests")
            .arg(&tests)
            .arg("--coverage")
            .arg(&coverage)
            .arg("--no-ty-filter")
            .arg("--no-cache") // isolate ordering from cache reuse
            // Smart ordering is on by default (timeout or not); pass the flag
            // explicitly to pin the behavior this test exercises even if the
            // default ever changes.
            .arg("--smart-order")
            .assert()
            .failure() // survivors → exit 1
            .stdout(contains("SURVIVED"));
    };

    run(); // builds the sidecar from learned kills
    assert!(
        sidecar.exists(),
        "first run must write the kill-order sidecar at {}",
        sidecar.display()
    );

    // The verdict-invariance check above passes even if ordering is a silent
    // no-op: a killer node id that pytest's `-rfE` summary reports differently
    // from the coverage-selected id would never match in `order()`, so the
    // sidecar would grow but never reorder — and the score wouldn't budge. Guard
    // that link directly: the recorded killer must be a real, `::`-formed test
    // id whose file resolves under the sample, i.e. exactly the shape a
    // coverage-selected id has and `order()` can lift. If pytest ever normalizes
    // ids differently from what we pass as positionals, this assertion trips.
    //
    // Sidecar shape: `{ file : { operator : { nodeid : count } } }`.
    let raw = std::fs::read_to_string(&sidecar).expect("sidecar readable");
    let ko: serde_json::Value = serde_json::from_str(&raw).expect("sidecar is valid JSON");
    let mut recorded = 0usize;
    for (_file, ops) in ko.as_object().expect("top level is a map") {
        for (_op, nodeids) in ops.as_object().expect("operator level is a map") {
            for (nodeid, count) in nodeids.as_object().expect("nodeid level is a map") {
                recorded += 1;
                assert!(
                    count.as_u64().is_some_and(|c| c >= 1),
                    "kill count for {nodeid:?} must be >= 1, got {count}"
                );
                // A well-formed pytest nodeid is `path::test`. A bare path (a
                // collection error) or a whitespace-truncated id would fail here.
                let (path_part, func_part) = nodeid.split_once("::").unwrap_or_else(|| {
                    panic!("recorded killer {nodeid:?} is not a `path::test` node id")
                });
                assert!(
                    !func_part.is_empty(),
                    "recorded killer {nodeid:?} has an empty test part"
                );
                // The path the id resolves to must exist under the sample tree.
                // A normalized-away id (wrong prefix, absolute rewrite) wouldn't.
                assert!(
                    sample.join(path_part).exists(),
                    "recorded killer {nodeid:?} resolves to {path_part:?}, which does not \
                     exist under the sample — pytest reported an id we can't match",
                );
            }
        }
    }
    assert!(
        recorded >= 1,
        "smart ordering must have learned at least one killer into the sidecar"
    );

    run(); // reads the sidecar to order; same verdict

    // Artifacts live under `tmp`, removed when the tempdir drops.
}

#[test]
#[ignore = "requires rstest (pytest-compatible drop-in) + ty on PATH; enable once env is set up"]
fn run_finds_known_survivor_with_rstest() {
    // `rstest` shares the pytest runner, so the same weak `in_range` boundary
    // test must leave a survivor — proving the `--runner rstest` path drives
    // the sample suite identically to `--runner pytest`.
    //
    // `run` writes `.fermut/` into the project; use a throwaway copy so nothing
    // lands in the checked-in sample or races a sibling test.
    let tmp = tempfile::tempdir().unwrap();
    let sample = tmp.path().join("sample");
    copy_dir(&sample_path(), &sample);
    Command::cargo_bin("fermut")
        .unwrap()
        .arg("run")
        .arg(sample.join("src"))
        .arg("--tests")
        .arg(sample.join("tests"))
        .arg("--runner")
        .arg("rstest")
        .arg("--no-ty-filter")
        .assert()
        .failure() // survivors → exit 1
        .stdout(contains("SURVIVED"));
}

#[test]
#[ignore = "requires pytest + coverage on PATH; enable once env is set up"]
fn baseline_reports_grade_and_anchors_trend() {
    // `baseline` writes `.coverage`, its fingerprint sidecar, and `.fermut/`
    // (history) into the project it runs against. Point it at a throwaway copy,
    // not the checked-in sample: writing into the shared tree pollutes a dev's
    // working dir and — under `cargo test`'s parallelism — races a sibling test
    // that copies the same sample, leaking a stale `.coverage` into that copy.
    let tmp = tempfile::tempdir().unwrap();
    let sample = tmp.path().join("sample");
    copy_dir(&sample_path(), &sample);

    // `baseline` builds coverage, runs a sampled mutation pass over covered
    // code, and emits the graded verdict. `--full` for determinism (no
    // sampling), JSON so we can assert on field names. The sample's weak
    // `in_range` boundary test guarantees survivors, so the score is well
    // under 100% — enough to exercise the gap + grade path.
    Command::cargo_bin("fermut")
        .unwrap()
        .arg("baseline")
        .arg(&sample)
        .arg("--full")
        .arg("--format")
        .arg("json")
        .assert()
        .success() // baseline reports; it does not gate, so exit 0
        .stdout(contains("\"mutation_score\""))
        .stdout(contains("\"grade\""))
        .stdout(contains("\"worst_files\""));

    // The run wrote a history entry flagged `baseline: true`; `trend` marks
    // it as the anchor in its table.
    Command::cargo_bin("fermut")
        .unwrap()
        .arg("trend")
        .arg(&sample)
        .assert()
        .success()
        .stdout(contains("[baseline]"));
}

#[test]
fn next_rejects_all_with_limit() {
    // `--all` and `--limit` are mutually exclusive; clap rejects the combo
    // before any report is read.
    Command::cargo_bin("fermut")
        .unwrap()
        .arg("next")
        .arg("nonexistent.json")
        .arg("--all")
        .arg("--limit")
        .arg("3")
        .assert()
        .failure()
        .stderr(contains("cannot be used with"));
}

#[test]
fn next_rejects_zero_limit() {
    // `--limit 0` is meaningless ("the zero best targets"); rejected before
    // the report is read, so a missing path is fine.
    Command::cargo_bin("fermut")
        .unwrap()
        .arg("next")
        .arg("nonexistent.json")
        .arg("--limit")
        .arg("0")
        .assert()
        .failure()
        .stderr(contains("--limit must be at least 1"));
}

#[test]
fn next_rejects_max_tokens_with_human_format() {
    // `--max-tokens` budgets the JSON output; pairing it with `--format human`
    // is rejected before the report is read.
    Command::cargo_bin("fermut")
        .unwrap()
        .arg("next")
        .arg("nonexistent.json")
        .arg("--max-tokens")
        .arg("500")
        .arg("--format")
        .arg("human")
        .assert()
        .failure()
        .stderr(contains("--max-tokens applies to JSON output only"));
}

/// Minimal report: one killed mutant (for the score denominator) plus two
/// boundary-shift survivors on adjacent lines in the same file — one cluster
/// of size 2. No coverage-skip outcome, so `coverage_selected` is false.
const NEXT_REPORT: &str = r#"{
  "outcomes": [
    { "status": "killed",
      "mutant": { "id": "a.py@10:boundary-shift:k", "file": "a.py",
        "operator": "boundary-shift", "range": [10, 12],
        "original": ">=", "replacement": ">", "line": 5 } },
    { "status": "survived",
      "mutant": { "id": "a.py@40:boundary-shift:s1", "file": "a.py",
        "operator": "boundary-shift", "range": [40, 42],
        "original": ">=", "replacement": ">", "line": 10 } },
    { "status": "survived",
      "mutant": { "id": "a.py@60:boundary-shift:s2", "file": "a.py",
        "operator": "boundary-shift", "range": [60, 62],
        "original": "<=", "replacement": "<", "line": 11 } }
  ]
}"#;

#[test]
fn next_ranks_cluster_from_report() {
    let dir = tempfile::tempdir().unwrap();
    let report = dir.path().join("report.json");
    std::fs::write(&report, NEXT_REPORT).unwrap();

    Command::cargo_bin("fermut")
        .unwrap()
        .arg("next")
        .arg(&report)
        .arg("--all")
        .assert()
        .success() // `next` exits 0 even with survivors
        .stdout(contains("\"rank\": 1"))
        .stdout(contains("\"cluster_size\": 2"))
        .stdout(contains("\"ease\": \"high\""))
        // two survivors share the cluster → one sibling on the representative
        .stdout(contains("\"sibling_ids\""))
        .stdout(contains("a.py@60:boundary-shift:s2"))
        // no coverage-skip outcome in the report → flag false in JSON
        .stdout(contains("\"coverage_selected\": false"));
}

// ---------------------------------------------------------------------------
// Per-subcommand smoke tests.
//
// The inline unit tests exercise each subcommand's internals; the tests above
// cover the two example trees and `next`'s ranking. What was missing was a
// thin, PATH-free smoke over the *surface* of the CLI: that every subcommand
// parses and dispatches, that the report/history readers emit the JSON schema
// their agent consumers depend on, and that the regression gate flips the exit
// code. These need neither pytest nor ty (they read fixtures on disk), so they
// run in plain `cargo test` with no `#[ignore]`.
// ---------------------------------------------------------------------------

/// Every subcommand name accepted by the top-level parser. Guards against a
/// variant that compiles but panics on dispatch, and — because the list is
/// spelled out — a subcommand removed or renamed without updating this test.
const SUBCOMMANDS: &[&str] = &[
    "run",
    "list",
    "mcp",
    "completions",
    "init",
    "trend",
    "score",
    "dashboard",
    "doctor",
    "baseline",
    "clean",
    "coverage",
    "merge",
    "pr-comment",
    "migrate",
    "show",
    "next",
    "explain",
    "autofix",
    "suggest",
];

#[test]
fn every_subcommand_prints_help() {
    for cmd in SUBCOMMANDS {
        Command::cargo_bin("fermut")
            .unwrap()
            .arg(cmd)
            .arg("--help")
            .assert()
            .success()
            .stdout(contains("Usage: fermut"))
            .stdout(contains(*cmd));
    }
}

#[test]
fn unknown_subcommand_is_rejected() {
    Command::cargo_bin("fermut")
        .unwrap()
        .arg("frobnicate")
        .assert()
        .failure()
        .stderr(contains("unrecognized subcommand"));
}

#[test]
fn completions_emit_scripts_for_each_shell() {
    // Each shell backend must produce a non-empty script with its signature
    // marker, so a broken clap_complete wiring can't ship a blank file.
    for (shell, marker) in [
        ("zsh", "#compdef fermut"),
        ("bash", "_fermut"),
        ("fish", "complete"),
    ] {
        Command::cargo_bin("fermut")
            .unwrap()
            .arg("completions")
            .arg(shell)
            .assert()
            .success()
            .stdout(contains(marker));
    }
}

#[test]
fn show_lists_survivors_and_score() {
    let dir = tempfile::tempdir().unwrap();
    let report = dir.path().join("report.json");
    std::fs::write(&report, NEXT_REPORT).unwrap();

    // Default view: survivors only, plus the summary/score footer.
    Command::cargo_bin("fermut")
        .unwrap()
        .arg("show")
        .arg(&report)
        .assert()
        .success()
        .stdout(contains("SURVIVED"))
        .stdout(contains("score:"));
}

#[test]
fn explain_requires_a_target() {
    let dir = tempfile::tempdir().unwrap();
    let report = dir.path().join("report.json");
    std::fs::write(&report, NEXT_REPORT).unwrap();

    // `explain` needs a mutant id to explain; omitting it is a parse error,
    // caught before the report is read.
    Command::cargo_bin("fermut")
        .unwrap()
        .arg("explain")
        .arg(&report)
        .assert()
        .failure()
        .stderr(contains("required arguments"));
}

#[test]
fn explain_emits_hint_and_skeleton_for_target() {
    let dir = tempfile::tempdir().unwrap();
    let report = dir.path().join("report.json");
    std::fs::write(&report, NEXT_REPORT).unwrap();

    // Source file `a.py` doesn't exist beside the report, so context is
    // degraded — but the operator hint and pytest skeleton are derived from
    // the mutant alone and must still render.
    Command::cargo_bin("fermut")
        .unwrap()
        .arg("explain")
        .arg(&report)
        .arg("a.py@40:boundary-shift:s1")
        .assert()
        .success()
        .stdout(contains("boundary-shift"))
        .stdout(contains("hint"))
        .stdout(contains("suggested test skeleton"));
}

#[test]
fn merge_combines_reports() {
    let dir = tempfile::tempdir().unwrap();
    let report = dir.path().join("report.json");
    std::fs::write(&report, NEXT_REPORT).unwrap();

    // Merging a report with itself doubles the outcome count; the merged JSON
    // carries a `summary` with the combined total.
    Command::cargo_bin("fermut")
        .unwrap()
        .arg("merge")
        .arg(&report)
        .arg(&report)
        .assert()
        .success()
        .stdout(contains("\"summary\""))
        .stdout(contains("\"total\""));
}

/// Two comparable history entries (same `config_hash`, same branch) where the
/// score drops 80% → 60%. The regression is real, not a config/scope artifact,
/// so `score` and the gate must both see it.
const HISTORY_REGRESSION: &str = concat!(
    r#"{"v":1,"timestamp":"2026-09-01T00:00:00Z","mutation_score":80.0,"killed":8,"survived":2,"timed_out":0,"skipped":0,"errored":0,"total":10,"config_hash":"abc","git_branch":"main","survivor_ids":["a.py@1:x:s"]}"#,
    "\n",
    r#"{"v":1,"timestamp":"2026-09-02T00:00:00Z","mutation_score":60.0,"killed":6,"survived":4,"timed_out":0,"skipped":0,"errored":0,"total":10,"config_hash":"abc","git_branch":"main","survivor_ids":["a.py@1:x:s","a.py@2:x:s","b.py@3:x:s"]}"#,
    "\n",
);

/// Write `HISTORY_REGRESSION` into a fresh project tree's `.fermut/history.jsonl`
/// and return the tempdir (kept alive by the caller) plus the project path.
fn history_regression_project() -> (tempfile::TempDir, PathBuf) {
    let dir = tempfile::tempdir().unwrap();
    let project = dir.path().join("proj");
    std::fs::create_dir_all(project.join(".fermut")).unwrap();
    std::fs::write(
        project.join(".fermut").join("history.jsonl"),
        HISTORY_REGRESSION,
    )
    .unwrap();
    (dir, project)
}

#[test]
fn score_json_reports_regression_signal() {
    let (_tmp, project) = history_regression_project();

    // JSON is the default; the agent reward signal must expose the delta, the
    // new-survivor set, and the `regressed` flag. `score` reports without
    // gating, so exit 0 even on a drop.
    Command::cargo_bin("fermut")
        .unwrap()
        .arg("score")
        .arg(&project)
        .assert()
        .success()
        .stdout(contains("\"delta\": -20.0"))
        .stdout(contains("\"regressed\": true"))
        .stdout(contains("\"new_survivors\""))
        .stdout(contains("b.py@3:x:s"));
}

#[test]
fn score_gate_fails_on_regression() {
    let (_tmp, project) = history_regression_project();

    // The 20-pt drop exceeds a 5-pt tolerance → the gate flips the exit code.
    Command::cargo_bin("fermut")
        .unwrap()
        .arg("score")
        .arg(&project)
        .arg("--fail-on-regression")
        .arg("5")
        .assert()
        .failure();
}

#[test]
fn score_gate_passes_within_tolerance() {
    let (_tmp, project) = history_regression_project();

    // A 25-pt tolerance absorbs the 20-pt drop → gate stays green.
    Command::cargo_bin("fermut")
        .unwrap()
        .arg("score")
        .arg(&project)
        .arg("--fail-on-regression")
        .arg("25")
        .assert()
        .success();
}

#[test]
fn trend_renders_history_table() {
    let (_tmp, project) = history_regression_project();

    Command::cargo_bin("fermut")
        .unwrap()
        .arg("trend")
        .arg(&project)
        .assert()
        .success()
        .stdout(contains("2 entries"))
        .stdout(contains("80.0%"))
        .stdout(contains("60.0%"))
        .stdout(contains("-20.0"));
}

#[test]
fn clean_removes_cache_but_keeps_history() {
    let (_tmp, project) = history_regression_project();
    let cache = project.join(".fermut").join("cache.json");
    std::fs::write(&cache, "{}").unwrap();

    Command::cargo_bin("fermut")
        .unwrap()
        .arg("clean")
        .arg(&project)
        .assert()
        .success()
        .stdout(contains("removed"));

    assert!(!cache.exists(), "clean must remove the result cache");
    assert!(
        project.join(".fermut").join("history.jsonl").exists(),
        "clean must preserve the history log"
    );
}

#[test]
fn init_writes_config_for_detected_layout() {
    let dir = tempfile::tempdir().unwrap();
    let project = dir.path();
    std::fs::write(
        project.join("pyproject.toml"),
        "[project]\nname = \"demo\"\n",
    )
    .unwrap();
    std::fs::create_dir_all(project.join("src")).unwrap();
    std::fs::create_dir_all(project.join("tests")).unwrap();

    Command::cargo_bin("fermut")
        .unwrap()
        .arg("init")
        .arg(project)
        .assert()
        .success()
        .stdout(contains("wrote"));

    assert!(
        project.join("fermut.toml").exists(),
        "init must write fermut.toml"
    );
}

#[test]
fn migrate_translates_mutmut_config() {
    let dir = tempfile::tempdir().unwrap();
    let project = dir.path();
    std::fs::write(
        project.join("pyproject.toml"),
        "[project]\nname = \"demo\"\n",
    )
    .unwrap();
    std::fs::write(
        project.join("setup.cfg"),
        "[mutmut]\npaths_to_mutate=src/\n",
    )
    .unwrap();

    Command::cargo_bin("fermut")
        .unwrap()
        .arg("migrate")
        .arg("mutmut")
        .arg(project)
        .assert()
        .success()
        .stdout(contains("source: mutmut"));

    assert!(
        project.join("fermut.toml").exists(),
        "migrate must write a starter fermut.toml"
    );
}

#[test]
fn doctor_reports_a_summary() {
    let dir = tempfile::tempdir().unwrap();
    let project = dir.path();
    std::fs::write(
        project.join("pyproject.toml"),
        "[project]\nname = \"demo\"\n",
    )
    .unwrap();

    // Doctor's exit code depends on which tools happen to be on PATH in the
    // test environment, so assert only on the stable diagnostic surface: it
    // runs the checks and prints a summary line.
    Command::cargo_bin("fermut")
        .unwrap()
        .arg("doctor")
        .arg(project)
        .assert()
        .stdout(contains("summary:"));
}

#[test]
fn dashboard_writes_self_contained_html() {
    let (_tmp, project) = history_regression_project();
    let out = project.join("dash.html");

    Command::cargo_bin("fermut")
        .unwrap()
        .arg("dashboard")
        .arg(&project)
        .arg("--output")
        .arg(&out)
        .assert()
        .success();

    let html = std::fs::read_to_string(&out).expect("dashboard HTML written");
    assert!(html.contains("<html"), "output must be an HTML document");
    // Self-contained: no external asset references.
    assert!(
        !html.contains("<script src="),
        "dashboard must not pull external scripts"
    );
}

#[test]
#[ignore = "requires pytest + pytest-cov + coverage on PATH; enable once env is set up"]
fn coverage_refresh_prunes_deleted_source_file() {
    // Issue #117: an incremental `fermut coverage` must drop a deleted source
    // file's rows from `.coverage`, not leave them for `coverage report` to
    // trip over (`couldnt-parse`) forever.
    let tmp = tempfile::tempdir().unwrap();
    let sample = tmp.path().join("sample");
    copy_dir(&sample_path(), &sample);
    std::fs::write(
        sample.join("src/helper.py"),
        "def triple(x):\n    return x * 3\n",
    )
    .unwrap();
    std::fs::write(
        sample.join("tests/test_helper.py"),
        "from src.helper import triple\n\n\ndef test_triple():\n    assert triple(2) == 6\n",
    )
    .unwrap();
    let coverage = sample.join(".coverage");
    let recorded = || -> Vec<String> {
        let conn = rusqlite::Connection::open(&coverage).unwrap();
        let mut stmt = conn.prepare("SELECT path FROM file").unwrap();
        stmt.query_map([], |r| r.get::<_, String>(0))
            .unwrap()
            .filter_map(|r| r.ok())
            .collect()
    };

    Command::cargo_bin("fermut")
        .unwrap()
        .arg("coverage")
        .arg(&sample)
        .assert()
        .success();
    assert!(
        recorded().iter().any(|p| p.ends_with("helper.py")),
        "full build must record helper.py: {:?}",
        recorded()
    );

    std::fs::remove_file(sample.join("src/helper.py")).unwrap();
    std::fs::remove_file(sample.join("tests/test_helper.py")).unwrap();
    Command::cargo_bin("fermut")
        .unwrap()
        .arg("coverage")
        .arg(&sample)
        .assert()
        .success()
        .stdout(contains("dropped 1 removed source file(s)"));

    let after = recorded();
    assert!(
        !after.iter().any(|p| p.ends_with("helper.py")),
        "deleted helper.py must leave the DB: {after:?}"
    );
    assert!(
        after.iter().any(|p| p.ends_with("calculator.py")),
        "live calculator.py must stay: {after:?}"
    );

    // Baseline advanced → the next refresh is a no-op.
    Command::cargo_bin("fermut")
        .unwrap()
        .arg("coverage")
        .arg(&sample)
        .assert()
        .success()
        .stdout(contains("up to date"));
}

#[test]
#[ignore = "requires pytest + pytest-cov + coverage on PATH; enable once env is set up"]
fn coverage_refresh_rebuilds_import_time_lines_of_changed_source() {
    // Import-time lines live under the shared `""` context, which `--cov-append`
    // unions. Shifting a source's lines must not leave its old line numbers
    // marked executed: the count of import-time lines stays the same.
    let tmp = tempfile::tempdir().unwrap();
    let sample = tmp.path().join("sample");
    copy_dir(&sample_path(), &sample);
    let coverage = sample.join(".coverage");
    let import_time_lines = || -> u32 {
        let conn = rusqlite::Connection::open(&coverage).unwrap();
        conn.query_row(
            "SELECT lb.numbits FROM line_bits lb \
             JOIN context c ON c.id = lb.context_id \
             JOIN file f ON f.id = lb.file_id \
             WHERE c.context = '' AND f.path LIKE '%calculator.py'",
            [],
            |r| r.get::<_, Vec<u8>>(0),
        )
        .unwrap()
        .iter()
        .map(|b| b.count_ones())
        .sum()
    };
    let refresh = || {
        Command::cargo_bin("fermut")
            .unwrap()
            .arg("coverage")
            .arg(&sample)
            .assert()
            .success();
    };

    refresh();
    let before = import_time_lines();
    assert!(before > 0, "full build must record import-time lines");

    let calc = sample.join("src/calculator.py");
    let src = std::fs::read_to_string(&calc).unwrap();
    std::fs::write(&calc, format!("{}{src}", "\n".repeat(30))).unwrap();
    refresh();

    assert_eq!(
        import_time_lines(),
        before,
        "shifted source must not keep its pre-change import-time lines"
    );
}
